### ISSUE TITLE
Archive this repository?

### ISSUE THREAD

**Issue by danielballan** [ContinuumIO/intake-postgres#18]
@martindurant in #17:

> Since postgresdapater is not maintained, I suggest we mothball this repo

Shall we put in a message in the GH repo description directing visitors to intake-sql instead, and then archive this?

**Comment by martindurant** [comment]
https://github.com/intake/intake-postgres/commit/fda7f7b2b6255544ea7ffd365a4ac8b2655fd226

**Comment by danielballan** [comment]
Ah, very good. Shall I archive it then to make its "un-maintained" status more obvious? No strong preference here.

**Comment by martindurant** [comment]
Go ahead. Would that suggest we should remove it from the list of known driver too?

**Comment by danielballan** [comment]
Yeah. I'll do the archiving if you do the "intake plugins directory" PR.

**Comment by martindurant** [comment]
I'll be going over Intake in general in the coming days to pick off work I can do, now I have a little time.
